server.port=8080
spring.application.name=wohackers-backend

# Serve o frontend separado em ../frontend
spring.web.resources.static-locations=file:../frontend/,classpath:/static/
spring.web.resources.cache.period=0

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false

# Permite snapshot com arquivos em base64 (edital/anexos)
server.tomcat.max-http-form-post-size=30MB
server.tomcat.max-swallow-size=30MB
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
server.port=${PORT:8080}
