server.port=8080
spring.application.name=wohackers-backend

# Serve o frontend separado em ../frontend
spring.web.resources.static-locations=file:../frontend/,classpath:/static/
spring.web.resources.cache.period=0

# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
